version: "3.7"
services:
  jenkins:
    #image: "jenkins/jenkins:lts"
    build:
      context: .
    ports:
      - "8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      cicd:
        aliases:
          - jenkins
     
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      cicd:
        aliases:
          - nginx
    depends_on:
      - jenkins    

networks:
  cicd:

volumes:
  jenkins_home: